/**
 * dsh-mobile-plus — browser half (client bundle).
 *
 * Ports the desktop-side part of `@linxin666/dsh-remote-web-ui`'s
 * `src/client/RemoteEntry.tsx` + `FooterRemoteEntry.tsx` (the sidebar foot
 * trigger + pairing panel), but for OUR plugin: the trigger carries our own
 * logo and the panel drives the independent `/mp/pair/*` routes (issue /
 * status), including a QR image generated by the host (`/mp/pair/issue` now
 * returns `qr` + `qrLocal` data URIs), so no third-party QR lib is inlined.
 *
 * The bundle is a classic script that registers one lazy factory with the
 * client module loader (see @deepseek-ai/dsh-client-modules); the only
 * external it requests is `react`, which the shell seeds statically.
 */
window.__ModuleLoader__.load({
  id: 'dsh-mobile-plus',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })

    var React = require('react')

    const MP_CSS = [
      '/* dsh-mobile-plus — sidebar foot trigger + pairing panel (design tokens only) */',
      '.mp-trigger{position:relative;flex:none;display:inline-flex;align-items:center;justify-content:center;width:36px;height:36px;border:none;border-radius:50%;padding:0;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;transition:background-color 120ms ease,color 120ms ease,box-shadow 120ms ease}',
      '.mp-trigger:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}',
      '.mp-trigger:active:not(:disabled){background:var(--dsw-alias-interactive-bg-active)}',
      '.mp-trigger:focus-visible{outline:none;box-shadow:0 0 0 2px var(--dsw-alias-bg-layer-2),0 0 0 4px var(--dsw-alias-brand-primary)}',
      '.mp-trigger[data-wide="wide"]{flex:1 1 auto;justify-content:flex-start;width:auto;min-width:0;border-radius:999px;gap:8px;padding:0 10px}',
      '.mp-trigger-label{font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
      '.mp-overlay{position:fixed;inset:0;z-index:1000;display:flex;align-items:center;justify-content:center}',
      '.mp-mask{position:absolute;inset:0;background:var(--dsw-alias-bg-mask-1);backdrop-filter:var(--dsw-mask-blur)}',
      '.mp-panel{position:relative;z-index:1;display:flex;flex-direction:column;gap:14px;width:480px;max-width:calc(100vw - 48px);max-height:calc(100vh - 48px);overflow:auto;box-sizing:border-box;padding:24px;border-radius:24px;background:var(--dsw-alias-bg-layer-2);box-shadow:var(--dsw-shadow-lv3);color:var(--dsw-alias-label-primary);font-size:14px;line-height:22px}',
      '.mp-header{display:flex;align-items:flex-start;gap:12px}',
      '.mp-heading{flex:1;min-width:0}',
      '.mp-title{margin:0;font-size:18px;font-weight:600;line-height:26px}',
      '.mp-subtitle{margin:2px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px}',
      '.mp-close{flex:none;display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border:none;border-radius:50%;padding:0;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;transition:background-color 120ms ease,color 120ms ease,box-shadow 120ms ease}',
      '.mp-close:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}',
      '.mp-close:active:not(:disabled){background:var(--dsw-alias-interactive-bg-active)}',
      '.mp-close:focus-visible{outline:none;box-shadow:0 0 0 2px var(--dsw-alias-bg-layer-2),0 0 0 4px var(--dsw-alias-brand-primary)}',
      '.mp-status{display:flex;align-items:center;justify-content:space-between;gap:12px}',
      '.mp-badge{display:inline-flex;flex:none;align-items:center;gap:6px;min-width:0;padding:2px 10px;border-radius:999px;font-size:12px;line-height:18px;white-space:nowrap}',
      '.mp-badge::before{content:"";width:8px;height:8px;border-radius:50%;background:currentColor}',
      '.mp-badge-waiting{color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-interactive-bg-hover)}',
      '.mp-badge-connected{color:var(--dsw-alias-state-success-primary);background:var(--dsw-alias-interactive-bg-hover)}',
      '.mp-card{display:flex;flex-direction:column;align-items:center;gap:10px;padding:16px;border:1px solid var(--dsw-alias-border-l2);border-radius:16px;background:var(--dsw-alias-bg-layer-1)}',
      '.mp-qr-wrap{display:flex;align-items:center;justify-content:center;padding:10px;border-radius:12px;background:var(--dsw-alias-bg-base)}',
      '.mp-qr{display:block;width:220px;height:220px}',
      '.mp-hint{margin:0;color:var(--dsw-alias-label-secondary);font-size:13px}',
      '.mp-expired{margin:0;color:var(--dsw-alias-state-error-primary);font-size:13px}',
      '.mp-links{display:flex;flex-direction:column;gap:8px}',
      '.mp-link-row{display:flex;align-items:center;gap:10px;min-width:0;padding:8px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-layer-1)}',
      '.mp-link-text{min-width:0;flex:1}',
      '.mp-link-label{display:block;margin-bottom:2px;color:var(--dsw-alias-label-secondary);font-size:12px}',
      '.mp-link-value{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-caption);font-family:var(--dsw-font-mono,ui-monospace,monospace);font-size:12px}',
      '.mp-copy{display:inline-flex;flex:none;align-items:center;gap:5px;min-height:28px;padding:0 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-button-elevated-fill);color:var(--dsw-alias-label-primary);font-size:12px;cursor:pointer}',
      '.mp-copy:hover:not(:disabled){background:var(--dsw-alias-button-floating-hover)}',
      '.mp-copy:disabled{opacity:.55;cursor:default}',
      '.mp-actions{display:flex;gap:8px;flex-wrap:wrap}',
      '.mp-btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;height:34px;padding:0 14px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-button-elevated-fill);color:var(--dsw-alias-label-primary);font-size:13px;cursor:pointer;white-space:nowrap;transition:background-color 120ms ease,border-color 120ms ease,box-shadow 120ms ease}',
      '.mp-btn:hover:not(:disabled){background:var(--dsw-alias-button-floating-hover)}',
      '.mp-btn:active:not(:disabled){background:var(--dsw-alias-interactive-bg-active)}',
      '.mp-btn:focus-visible{outline:none;box-shadow:0 0 0 2px var(--dsw-alias-bg-layer-2),0 0 0 4px var(--dsw-alias-brand-primary)}',
      '.mp-btn:disabled{opacity:.55;cursor:default}',
      '.mp-btn-primary{border-color:var(--dsw-alias-brand-primary);background:var(--dsw-alias-brand-primary);color:#fff}',
      '.mp-error{margin:0;color:var(--dsw-alias-state-error-primary);font-size:13px}',
      '.mp-note{margin:0;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}',
      '@media (prefers-reduced-motion: reduce){.mp-trigger,.mp-close,.mp-copy,.mp-btn{transition:none}}',
    ].join('')
    if (typeof document !== 'undefined' && document.querySelector('style[data-plugin-css="dsh-mobile-plus/ui.css"]') === null) {
      const tag = document.createElement('style')
      tag.dataset.plugin = 'dsh-mobile-plus'
      tag.dataset.pluginCss = 'dsh-mobile-plus/ui.css'
      tag.textContent = MP_CSS
      document.head.appendChild(tag)
    }

    var h = React.createElement

    /** Monochrome trigger mark: phone + photo + plus (currentColor). */
    function TriggerMark({ size = 18 }) {
      return h('svg', { width: size, height: size, viewBox: '0 0 20 20', fill: 'none', 'aria-hidden': 'true' },
        h('path', { d: 'M7.6 1.9h4.8a2.4 2.4 0 0 1 2.4 2.4v11.4a2.4 2.4 0 0 1-2.4 2.4H7.6a2.4 2.4 0 0 1-2.4-2.4V4.3a2.4 2.4 0 0 1 2.4-2.4z', stroke: 'currentColor', strokeWidth: 1.35 }),
        h('circle', { cx: 12.2, cy: 6.4, r: 0.9, fill: 'currentColor' }),
        h('path', { d: 'M6.9 11.9l1.9-2.4 1.2 1.5 1.4-1.7 2 2.4', stroke: 'currentColor', strokeWidth: 1.3, strokeLinecap: 'round', strokeLinejoin: 'round' }),
        h('path', { d: 'M16 3v4M14 5h4', stroke: 'currentColor', strokeWidth: 1.6, strokeLinecap: 'round' })
      )
    }

    /** Brand tile: rounded gradient badge with the white glyph (our logo). */
    function TileLogo({ size = 24 }) {
      const gid = React.useId()
      return h('svg', { width: size, height: size, viewBox: '0 0 48 48', 'aria-hidden': 'true', style: { display: 'block', flex: 'none' } },
        h('defs', null,
          h('linearGradient', { id: gid, x1: '0', y1: '0', x2: '1', y2: '1' },
            h('stop', { offset: '0', stopColor: '#3E7BFA' }),
            h('stop', { offset: '1', stopColor: '#7A5CFF' }))),
        h('rect', { x: 1, y: 1, width: 46, height: 46, rx: 13, fill: `url(#${gid})` }),
        h('path', { d: 'M19.2 10.2h9.6a3 3 0 0 1 3 3v21.6a3 3 0 0 1-3 3h-9.6a3 3 0 0 1-3-3v-21.6a3 3 0 0 1 3-3z', fill: 'none', stroke: '#ffffff', strokeWidth: 2.4 }),
        h('circle', { cx: 27.2, cy: 18.6, r: 1.4, fill: '#ffffff' }),
        h('path', { d: 'M20.8 27.4l2.3-2.9 1.5 1.8 1.7-2.1 2.4 2.9', fill: 'none', stroke: '#ffffff', strokeWidth: 1.7, strokeLinecap: 'round', strokeLinejoin: 'round' }),
        h('circle', { cx: 36.6, cy: 11.4, r: 6, fill: '#ffffff' }),
        h('path', { d: 'M36.6 8.2v6.4M33.4 11.4h6.4', fill: 'none', stroke: '#5B6CF0', strokeWidth: 2.2, strokeLinecap: 'round' })
      )
    }

    async function copyText(text) {
      if (window.isSecureContext && navigator.clipboard && navigator.clipboard.writeText) {
        try {
          await navigator.clipboard.writeText(text)
          return true
        } catch { /* fall through */ }
      }
      try {
        const ta = document.createElement('textarea')
        ta.value = text
        ta.style.position = 'fixed'
        ta.style.opacity = '0'
        document.body.appendChild(ta)
        ta.select()
        const ok = document.execCommand('copy')
        ta.remove()
        return ok
      } catch {
        return false
      }
    }

    async function issuePair() {
      const res = await fetch('/mp/pair/issue', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: '{}',
      })
      const data = await res.json()
      if (!data.ok) throw new Error(data.code || 'issue failed')
      return data
    }

    async function pairStatus() {
      try {
        const res = await fetch('/mp/pair/status', { credentials: 'same-origin' })
        const data = await res.json()
        return {
          deviceCount: typeof data.deviceCount === 'number' ? data.deviceCount : 0,
          paired: data.paired === true,
        }
      } catch {
        return { deviceCount: 0, paired: false }
      }
    }

    /** The pairing panel: issue link + QR (host-rendered), copy, live status. */
    function MpPanel({ state, issue, copied, busy, error, onClose, onIssue, onRefresh, onCopy }) {
      const s = state || { deviceCount: 0, paired: false }
      const minutesLeft = issue?.expiresAt ? Math.max(1, Math.round((issue.expiresAt - Date.now()) / 60000)) : undefined
      return h('div', { className: 'mp-overlay', role: 'presentation' },
        h('div', { className: 'mp-mask', 'aria-hidden': 'true', onClick: onClose }),
        h('div', { className: 'mp-panel', role: 'dialog', 'aria-modal': 'true', 'aria-label': '手机发图远程' },
          h('div', { className: 'mp-header' },
            h(TileLogo, { size: 30 }),
            h('div', { className: 'mp-heading' },
              h('h2', { className: 'mp-title' }, ['手机发图远程']),
              h('p', { className: 'mp-subtitle' }, ['独立插件 · 支持文字与图片 · 不影响原 /m/'])),
            h('button', { type: 'button', className: 'mp-close', 'aria-label': '关闭', onClick: onClose }, ['×'])),
          h('div', { className: 'mp-status' },
            h('span', { className: `mp-badge ${s.deviceCount > 0 ? 'mp-badge-connected' : 'mp-badge-waiting'}` },
              [s.deviceCount > 0 ? `已连接 · ${s.deviceCount} 台设备` : '等待配对']),
            minutesLeft !== undefined ? h('span', { className: 'mp-hint' }, [`链接约 ${minutesLeft} 分钟后过期`]) : null),
          issue
            ? h('div', { className: 'mp-card' },
                h('div', { className: 'mp-qr-wrap' }, h('img', { className: 'mp-qr', src: issue.qr, alt: '手机扫码配对二维码' })),
                h('p', { className: 'mp-hint' }, ['用手机浏览器打开 /mp/ 或扫上面的二维码完成配对（一次性，约 2 小时有效）']),
                h('div', { className: 'mp-links' },
                  h('div', { className: 'mp-link-row' },
                    h('div', { className: 'mp-link-text' },
                      h('span', { className: 'mp-link-label' }, ['公网链接（人在外面用）']),
                      h('span', { className: 'mp-link-value' }, [issue.url])),
                    h('button', { type: 'button', className: 'mp-copy', disabled: copied === 'url', onClick: () => onCopy('url', issue.url) }, [copied === 'url' ? '已复制' : '复制'])),
                  h('div', { className: 'mp-link-row' },
                    h('div', { className: 'mp-link-text' },
                      h('span', { className: 'mp-link-label' }, ['本机链接（局域网调试用）']),
                      h('span', { className: 'mp-link-value' }, [issue.localUrl])),
                    h('button', { type: 'button', className: 'mp-copy', disabled: copied === 'local', onClick: () => onCopy('local', issue.localUrl) }, [copied === 'local' ? '已复制' : '复制']))),
                h('div', { className: 'mp-actions' },
                  h('button', { type: 'button', className: 'mp-btn', disabled: busy, onClick: onRefresh }, ['刷新链接'])))
            : h('div', { className: 'mp-actions' },
                h('button', { type: 'button', className: 'mp-btn mp-btn-primary', disabled: busy, onClick: onIssue }, [busy ? '生成中…' : '生成配对链接'])),
          error ? h('p', { className: 'mp-error' }, [error]) : null,
          h('p', { className: 'mp-note' }, ['手机端发送的图片会写入工作区的 .dsh-mobile-inbox/，最新一张为 latest.jpg'])))
    }

    /** Sidebar foot entry: our logo trigger + the pairing panel (old-plugin port). */
    function MpEntry(props) {
      const wide = props?.wide === true
      const [open, setOpen] = React.useState(false)
      const [busy, setBusy] = React.useState(false)
      const [issue, setIssue] = React.useState(null)
      const [state, setState] = React.useState({ deviceCount: 0, paired: false })
      const [error, setError] = React.useState('')
      const [copied, setCopied] = React.useState('')

      const mint = React.useCallback(async () => {
        setBusy(true)
        setError('')
        try {
          const data = await issuePair()
          setIssue(data)
        } catch (err) {
          setError(String(err?.message || err))
          setIssue(null)
        } finally {
          setBusy(false)
        }
      }, [])

      const openPanel = React.useCallback(() => {
        setOpen(true)
        void mint()
      }, [mint])

      const closePanel = React.useCallback(() => setOpen(false), [])

      const handleCopy = React.useCallback((key, url) => {
        void copyText(url).then((ok) => {
          if (!ok) return
          setCopied(key)
          window.setTimeout(() => setCopied(''), 1500)
        })
      }, [])

      React.useEffect(() => {
        if (!open) return undefined
        const timer = window.setInterval(() => {
          void pairStatus().then(setState)
        }, 3000)
        void pairStatus().then(setState)
        return () => { window.clearInterval(timer) }
      }, [open])

      return h('div', { className: 'mp-entry', style: { display: 'contents' } },
        h('button', {
          type: 'button',
          className: 'mp-trigger',
          'data-wide': wide ? 'wide' : 'rail',
          'aria-label': '手机发图远程',
          'aria-expanded': open,
          title: '手机发图远程（配对）',
          onClick: openPanel,
        },
          wide
            ? h(React.Fragment, null, h(TileLogo, { size: 18 }), h('span', { className: 'mp-trigger-label' }, ['手机远程']))
            : h(TileLogo, { size: 18 })),
        open ? h(MpPanel, { state, issue, copied, busy, error, onClose: closePanel, onIssue: mint, onRefresh: mint, onCopy: handleCopy }) : null)
    }

    const inject = ['slots']

    function apply(ctx) {
      ctx.slots.inject('sidebar.footer.action', () => {
        let dispose
        try {
          dispose = ctx.slots.register({ name: 'sidebar.footer.action', id: 'dsh-mobile-plus' }, MpEntry)
        } catch {
          dispose = undefined
        }
        return () => { if (dispose) dispose() }
      })
    }

    exports.apply = apply
    exports.inject = inject
    return module.exports
  }
})
